
version: '3'

services:
  mysqldb:
    image: mysql:8.0
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_DATABASE=testDB
      - MYSQL_PASSWORD=abcd1234
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testDB
      - spring.datasource.username=root
      - spring.datasource.password=abcd1234
      - application.security.jwt.access-token.expiration=86400000
      - application.security.jwt.refresh-token.expiration=604800000